baseURL = "https://blog.yixiangao.cc/"
locale = "zh‑cn"
title = "易贤的博客"
theme = "FixIt"

[pagination]
  pageSize = 6

[params.homepage]
layout = "grid"          # 开启网格卡片，就是截图里的卡片效果
gridColumn = 2           # md以上屏幕2列卡片
pagination = true

[params]
  default_theme = "auto"
  enableDarkmode = true

[[menu.main]]
  [[menu.main]]
    name = "首页"
    weight = 1
    url = "/"
  [[menu.main]]
    name = "文章"
    weight = 2
    url = "/posts/"
