baseURL = "https://blog.yixiangao.cc/"
languageCode = "zh-cn"
title = "易贤博客"
theme = "PaperMod"

[params]
  env = "production"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2
